# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
- name: testFilter
  value: Category!=Skip 

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
   # Write your commands here
   dotnet build
   IFS=$'\n'
   ALL_ARRAY=(`dotnet test --list-tests`)
   FILTERED_ARRAY=(`dotnet test --list-tests --filter "${{ variables.testFilter }}"`)
   SKIPPED_ARRAY=(`echo ${ALL_ARRAY[@]} ${FILTERED_ARRAY[@]} | sed 's/ /\n/g' | sort | uniq -u`)
   len=${#SKIPPED_ARRAY[@]}
   if [ $len -gt 0 ]
   then
     echo "##vso[task.logissue type=warning] found ${len} skipped test(s) by this filter ${{ variables.testFilter}} %0D%0A ${SKIPPED_ARRAY[*]}"
   fi

  displayName: 'Bash Script'
