# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
- name: testFilter
  value: Category!=Skip 

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
    dotnet build
    chmod 755 ./run.sh
    ./run.sh ${{ variables.testFilter}}

  displayName: 'Bash Script'
