# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Install SpecFlow.Plus.LivingDoc.CLI
      run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
    - name: Test
      run: dotnet test
    - name: Generate LivingDoc
      run: livingdoc feature-folder ./Features --output-directory ./LivingDoc --clean --title "MyProject LivingDoc"
      working-directory: ./srcBDD/JobBDD
    - name: Upload LivingDoc artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: CoverageReport # Artifact name        
        path: '**/LivingDoc.html' # Directory containing files to upload
